### ISSUE TITLE
Server - Failed to save chunk

### ISSUE THREAD

**Issue by stdafx-h** [elucent/eidolon#129]
**Describe the bug**
Chunk saving issue

**To Reproduce**
This issue seems to happen whenever a player leaves the game. Though performing a manual save seems to function normally and doesn't throw this.

**Environment**
Mod Version: eidolon-0.2.7.jar
Server Type: Magma 1.16.5 - v75c9e73

**Crash Report**
```
[24Nov2021 09:27:27.561] [Server thread/ERROR] [net.minecraft.world.server.ChunkManager/]: Failed to save chunk [-9, -11]
java.util.concurrent.CompletionException: java.lang.AbstractMethodError: Method elucent/eidolon/tile/WoodenStandTileEntity.getViewers()Ljava/util/List; is abstract
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_311]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:1.8.0_311]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_311]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_311]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_311]
	at net.minecraft.world.server.ChunkManager.func_223155_b(ChunkManager.java:425) ~[?:?]
	at net.minecraft.world.server.ChunkManager.func_219204_a(ChunkManager.java:392) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:371) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:423) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1118) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:381) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1032) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:869) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:286) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]
Caused by: java.lang.AbstractMethodError: Method elucent/eidolon/tile/WoodenStandTileEntity.getViewers()Ljava/util/List; is abstract
	at elucent.eidolon.tile.WoodenStandTileEntity.getViewers(WoodenStandTileEntity.java) ~[eidolon:0.2.7]
	at net.minecraft.world.server.ServerWorld.func_217466_a(ServerWorld.java:1027) ~[?:?]
	at net.minecraft.world.server.ChunkManager.func_219185_a(ChunkManager.java:446) ~[?:?]
	... 13 more
```

Full log: https://gist.github.com/stdafx-h/f4793ef046b7fa97129b50e797b55ce4

**Comment by stdafx-h** [comment]
I'm pretty sure this issue has to do with the fact I'm running through Magma and has nothing to do with the mod itself.
