### ISSUE TITLE
Shift+Right Clicking the wrong item into the Apothecary's UI crashes the game

### ISSUE THREAD

**Issue by Tsunamori74** [elucent/eidolon#32]
Here's the report. It's a big pack so I'm sorry I can't narrow it down a lil bit more. I'll do more testing in a bit.

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 1/3/21 10:12 PM
Description: Container click

java.lang.IndexOutOfBoundsException: Index: 40, Size: 40
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_51] {re:computing_frames}
	at net.minecraft.inventory.container.Container.func_75135_a(Container.java:501) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at elucent.eidolon.gui.WoodenBrewingStandContainer.func_82846_b(WoodenBrewingStandContainer.java:78) ~[?:0.2.4] {re:classloading}
	at net.minecraft.inventory.container.Container.func_241440_b_(Container.java:255) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.inventory.container.Container.func_184996_a(Container.java:160) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.multiplayer.PlayerController.func_187098_a(PlayerController.java:379) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_184098_a(ContainerScreen.java:539) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin,pl:mixin:APP:charm.mixins.json:accessor.ContainerScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_231044_a_(ContainerScreen.java:336) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin,pl:mixin:APP:charm.mixins.json:accessor.ContainerScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$13390/641312651.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$13389/432739895.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$11267/1921283275.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:384) ~[?:?] {re:classloading,xf:OptiFine:default,xf:optiforge:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:client.MixinMinecraft,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:client.MixinMinecraft,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.28.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$480/1557752641.call(Unknown Source) [forge-1.16.4-35.1.28.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_51] {re:computing_frames}
	at net.minecraft.inventory.container.Container.func_75135_a(Container.java:501) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at elucent.eidolon.gui.WoodenBrewingStandContainer.func_82846_b(WoodenBrewingStandContainer.java:78) ~[?:0.2.4] {re:classloading}
	at net.minecraft.inventory.container.Container.func_241440_b_(Container.java:255) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
-- Click info --
Details:
	Menu Type: eidolon:wooden_brewing_stand
	Menu Class: elucent.eidolon.gui.WoodenBrewingStandContainer
	Slot Count: 40
	Slot: 4
	Button: 0
	Type: QUICK_MOVE
Stacktrace:
	at net.minecraft.inventory.container.Container.func_184996_a(Container.java:160) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.multiplayer.PlayerController.func_187098_a(PlayerController.java:379) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_184098_a(ContainerScreen.java:539) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin,pl:mixin:APP:charm.mixins.json:accessor.ContainerScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_231044_a_(ContainerScreen.java:336) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin,pl:mixin:APP:charm.mixins.json:accessor.ContainerScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$13390/641312651.run(Unknown Source) ~[?:?] {}

-- Affected screen --
Details:
	Screen name: elucent.eidolon.gui.WoodenBrewingStandScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$13389/432739895.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$11267/1921283275.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102) ~[?:?] {re:mixin,re:classloading}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Tsunamori74'/393, l='ClientLevel', x=-664.74, y=65.00, z=440.16]]
	Chunk stats: Client Chunk Cache: 1369, 1023
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,63,0), Chunk: (at 0,3,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 79707 game time, 14328 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:client.MixinMinecraft,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:client.MixinMinecraft,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.28.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$480/1557752641.call(Unknown Source) [forge-1.16.4-35.1.28.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 694059560 bytes (661 MB) / 4515168256 bytes (4306 MB) up to 7516192768 bytes (7168 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8064m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.4_HD_U_G5.jar OptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.4-0.4.4.jar optiforge TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.28.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.4-0.4.4.jar FakeOptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.4-0.4.4.jar optiforgewrapper TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.28
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		CyclopsCore-1.16.4-1.9.4.jar                      |Cyclops Core                  |cyclopscore                   |1.9.4               |DONE      |NOSIGNATURE
		QuarkOddities-1.16.3.jar                          |Quark Oddities                |quarkoddities                 |1.16.3              |DONE      |NOSIGNATURE
		NetherPortalFix_1.16.3-7.2.1.jar                  |NetherPortalFix               |netherportalfix               |7.2.1               |DONE      |NOSIGNATURE
		infernal-expansion-forge-1.0.0.jar                |Infernal Expansion            |infernalexp                   |Release 1.0 for 1.16|DONE      |NOSIGNATURE
		connectiblechains-1.0.jar                         |Connectible Chains            |connectiblechains             |1.0                 |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.63.jar                           |Just Enough Items             |jei                           |7.6.1.63            |DONE      |NOSIGNATURE
		OptiForge-MC1.16.4-0.4.4.jar                      |OptiForge                     |optiforge                     |0.4.4               |DONE      |NOSIGNATURE
		abnormals_core-1.16.4-3.0.5.jar                   |Abnormals Core                |abnormals_core                |3.0.5               |DONE      |NOSIGNATURE
		buzzier_bees-1.16.4-3.0.0.jar                     |Buzzier Bees                  |buzzier_bees                  |3.0.0               |DONE      |NOSIGNATURE
		berry_good-1.16.4-4.0.0.jar                       |Berry Good                    |berry_good                    |4.0.0               |DONE      |NOSIGNATURE
		cookielicious-1.16.4-1.2.0.jar                    |Cookielicious                 |cookielicious                 |1.1.3               |DONE      |NOSIGNATURE
		placeableblazerods_1.16.4-1.0.jar                 |Placeable Blaze Rods          |placeableblazerods            |1.0                 |DONE      |NOSIGNATURE
		ContentTweaker-1.16-1.0.0.develop.10.jar          |ContentTweaker                |contenttweaker                |1.0.0.develop.10    |DONE      |NOSIGNATURE
		Brazier-2.2.0.jar                                 |Brazier                       |brazier                       |2.2.0               |DONE      |NOSIGNATURE
		windowlogging-mc1.16.3_v0.0.2.jar                 |Windowlogging                 |windowlogging                 |0.0.2               |DONE      |NOSIGNATURE
		strawgolem-1.16-1.9.jar                           |Straw Golem                   |strawgolem                    |1.16-1.9            |DONE      |NOSIGNATURE
		guiclock_1.16.4-2.0.jar                           |GUI Clock                     |guiclock                      |2.0                 |DONE      |NOSIGNATURE
		noautojump-1.16.3-1.jar                           |No Auto-Jump                  |noautojump                    |1.16.3-1            |DONE      |NOSIGNATURE
		extraboats-1.16.4-2.0.0.jar                       |Extra Boats                   |extraboats                    |2.0.0               |DONE      |NOSIGNATURE
		create-mc1.16.3_v0.3b.jar                         |Create                        |create                        |mc1.16.3_v0.3b      |DONE      |NOSIGNATURE
		BetterCaves-1.16.3-1.0.6.jar                      |YUNG's Better Caves           |bettercaves                   |1.16.3-1.0.6        |DONE      |NOSIGNATURE
		shutupexperimentalsettings-1.0.1.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.1               |DONE      |NOSIGNATURE
		Controlling-7.0.0.11.jar                          |Controlling                   |controlling                   |7.0.0.11            |DONE      |NOSIGNATURE
		Placebo-1.16.3-4.3.3.jar                          |Placebo                       |placebo                       |4.3.3               |DONE      |NOSIGNATURE
		citadel-1.5.3.jar                                 |Citadel                       |citadel                       |1.5.3               |DONE      |NOSIGNATURE
		alexsmobs-1.3.0.jar                               |Alex's Mobs                   |alexsmobs                     |1.3.0               |DONE      |NOSIGNATURE
		SereneSeasons-1.16.4-4.0.0.86-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.4-4.0.0.85     |DONE      |NOSIGNATURE
		guicompass_1.16.4-1.3.jar                         |GUI Compass                   |guicompass                    |1.3                 |DONE      |NOSIGNATURE
		gemsnjewels-1.16.4-0.19.0.jar                     |Gems & Jewels                 |gemsnjewels                   |0.19.0              |DONE      |NOSIGNATURE
		sophisticatedbackpacks-1.16.4-1.2.1.124.jar       |Sophisticated Backpacks       |sophisticatedbackpacks        |1.16.4-1.2.1.124    |DONE      |NOSIGNATURE
		bedspreads-forge-1.16.4-5.1.0.1.jar               |Bedspreads                    |bedspreads                    |1.16.4-5.1.0.1      |DONE      |NOSIGNATURE
		iceandfire-2.1.4-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.4-1.16.4        |DONE      |NOSIGNATURE
		voyage-1.16.4-1.0.3.jar                           |Voyage                        |voyage                        |1.0.3               |DONE      |NOSIGNATURE
		Toast-Control-1.16.3-4.3.0.jar                    |Toast Control                 |toastcontrol                  |4.3.0               |DONE      |NOSIGNATURE
		JEITweaker-1.16.4-1.0.1.5.jar                     |JEI Tweaker                   |jeitweaker                    |1.0.1.5             |DONE      |NOSIGNATURE
		inventorypets-2.0.9.jar                           |Inventory Pets                |inventorypets                 |2.0.9               |DONE      |NOSIGNATURE
		CraftTweaker-1.16.4-7.0.0.63.jar                  |CraftTweaker                  |crafttweaker                  |7.0.0.63            |DONE      |NOSIGNATURE
		chat_heads_forge-0.2.0.jar                        |Chat Heads                    |chat_heads                    |0.2.0               |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.28-universal.jar                |Forge                         |forge                         |35.1.28             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		amb-1.16.4-0.1.1.jar                              |Aurum's More Blocks           |amb                           |1.16.4-0.1.1        |DONE      |NOSIGNATURE
		supplementaries-0.9.17.jar                        |Supplementaries               |supplementaries               |0.9.17              |DONE      |NOSIGNATURE
		Buddycards-1.16.4-1.3.2.jar                       |Buddycards                    |buddycards                    |1.16.4-1.3.2        |DONE      |NOSIGNATURE
		xercamusic-1.16.4-1.1.jar                         |Xerca's Music Maker Mod       |xercamusic                    |1.16.4-1.1          |DONE      |NOSIGNATURE
		betterendforge-1.16.4-1.2.0.jar                   |BetterEnd Forge Port          |betterendforge                |1.16.4-1.2.0        |DONE      |NOSIGNATURE
		ColossalChests-1.16.4-1.7.12.jar                  |ColossalChests                |colossalchests                |1.7.12              |DONE      |NOSIGNATURE
		neapolitan-1.16.4-2.0.1.jar                       |Neapolitan                    |neapolitan                    |2.0.1               |DONE      |NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.2.0.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.2.0      |DONE      |b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		forge-1.16.4-35.1.28-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		upgrade_aquatic-1.16.4-3.0.0.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.0.0               |DONE      |NOSIGNATURE
		cofh_core-1.16.3-1.1.6.jar                        |CoFH Core                     |cofh_core                     |1.1.6               |DONE      |NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |DONE      |NOSIGNATURE
		FarmersDelight-1.16.3-0.2.4b.jar                  |Farmer's Delight              |farmersdelight                |1.16.3-0.2.4b       |DONE      |NOSIGNATURE
		MouseTweaks-2.13-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.13                |DONE      |NOSIGNATURE
		snailmail-1.16.4-1.0.0.jar                        |Snail Mail                    |snailmail                     |1.0.0               |DONE      |NOSIGNATURE
		archers_paradox-1.16.3-1.1.1.jar                  |Archer's Paradox              |archers_paradox               |1.1.1               |DONE      |NOSIGNATURE
		Botania-1.16.4-410.jar                            |Botania                       |botania                       |1.16.4-410          |DONE      |NOSIGNATURE
		fairylights-4.0.4-1.16.4.jar                      |Fairy Lights                  |fairylights                   |4.0.4               |DONE      |NOSIGNATURE
		atmospheric-1.16.4-3.0.0.jar                      |Atmospheric                   |atmospheric                   |3.0.0               |DONE      |NOSIGNATURE
		jeiintegration_1.16.4-6.1.1.11.jar                |JEI Integration               |jeiintegration                |6.1.1.11            |DONE      |NOSIGNATURE
		curios-forge-1.16.4-4.0.3.3.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.3      |DONE      |NOSIGNATURE
		eidolon-0.2.4.jar                                 |Eidolon                       |eidolon                       |0.2.4               |DONE      |NOSIGNATURE
		savageandravage-1.16.4-3.0.0.jar                  |Savage & Ravage               |savageandravage               |3.0.0               |DONE      |NOSIGNATURE
		Patchouli-1.16.4-48.jar                           |Patchouli                     |patchouli                     |1.16.4-48           |DONE      |NOSIGNATURE
		enchantedwolves-1.1.0.1.jar                       |Enchanted Wolves              |enchantedwolves               |1.1.0.1             |DONE      |NOSIGNATURE
		collective-1.16.4-1.53.jar                        |Collective                    |collective                    |1.53                |DONE      |NOSIGNATURE
		petrevivemod-1.1.jar                              |Pet Revive Mod                |petrevive                     |1.0                 |DONE      |NOSIGNATURE
		autumnity-1.16.4-2.0.0.jar                        |Autumnity                     |autumnity                     |2.0.0               |DONE      |NOSIGNATURE
		polymorph-forge-1.16.4-0.22.jar                   |Polymorph                     |polymorph                     |1.16.4-0.22         |DONE      |NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
		Quark-r2.4-286.jar                                |Quark                         |quark                         |r2.4-286            |DONE      |NOSIGNATURE
		StorageDrawers-1.16.3-8.2.1.jar                   |Storage Drawers               |storagedrawers                |8.2.1               |DONE      |NOSIGNATURE
		DoubleSlabs-1.16-3.4.10.jar                       |Double Slabs                  |doubleslabs                   |3.4.10              |DONE      |NOSIGNATURE
		simplytea-1.16.4-2.3.2.jar                        |Simply Tea                    |simplytea                     |2.3.2               |DONE      |NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		chunkloaders-1.1.3-mc1.16.4.jar                   |Chunk Loaders                 |chunkloaders                  |1.1.3               |DONE      |NOSIGNATURE
		the_bumblezone-1.16.4-2.2.8.jar                   |The Bumblezone                |the_bumblezone                |1.16.4-2.2.8        |DONE      |NOSIGNATURE
		charm-forge-1.16.4-2.2.1.jar                      |Charm                         |charm                         |2.2.1               |DONE      |NOSIGNATURE
		charmonium-forge-1.16.4-2.2.1.jar                 |Charmonium                    |charmonium                    |2.2.1               |DONE      |NOSIGNATURE
		extremeSoundMuffler-3.3_Forge-1.16.4.jar          |Extreme Sound Muffler         |extremesoundmuffler           |3.3_forge-1.16.4    |DONE      |NOSIGNATURE
		CosmeticArmorReworked-1.16.4-v1.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.4-v1           |DONE      |5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		chiselsandbits-0.2.8-RELEASE.jar                  |Chisels & bits                |chiselsandbits                |NONE                |DONE      |NOSIGNATURE
		BetterMineshafts-Forge-1.16.3-1.1.1.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.3-1.1.1        |DONE      |NOSIGNATURE
	Crash Report UUID: f06e3960-f372-4ada-a104-d166b2ea0e27
	Patchouli open book context: n/a
	Launched Version: forge-35.1.28
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.89, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, inspirations:config_resources (incompatible), quark:emote_resources (incompatible), resourcefulbees, file/VanillaTweaks_r244988.zip
	Current Language: English (US)
	CPU: 4x AMD A10-9700 RADEON R7, 10 COMPUTE CORES 4C+6G 
	OptiFine Version: OptiFine_1.16.4_HD_U_G5
	OptiFine Build: 20201106-171901
	Render Distance Chunks: 16
	Mipmaps: 2
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 460.89
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by elucent** [comment]
Fixed in 0.2.5, please update the mod.
